version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/docs/"
    schedule:
      interval: "monthly"

    groups:
      eslint:
        patterns:
          - 'eslint*'
          - 'globals'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - '@rushstack/eslint-patch'
          - '@types/eslint'
      stylelint:
        patterns:
          - 'stylelint*'
      vue:
        patterns:
          - 'vue*'
          - '@vue/*'
      vite:
        patterns:
          - 'vite*'
          - '@vitejs/*'
      vueuse:
        patterns:
          - '@vueuse/*'
